### ISSUE TITLE
Posible bug

### ISSUE THREAD

**Issue by davidcreager** [toddaustin07/MQTT_SmartApp#1]
Apologies, I have now lost the log *sigh*   However, my environment gave a log error trying to publish a message where the value was supposed to be a string or buffer and was in fact a number (It was a valid reading, but it might not be a smartthings proper sensor reading - don't ask -:) )

I changed the following code in  your sendMQTT Function in mqttout.js to guard this and it seems to have worked

Your code line 220
` mqttClient.publish(topic, msg_tosend.event.value, pub_options, (err) => {`

My change 
`const valToSend = (typeof(msg_tosend.event.value) == "number") ? Number(msg_tosend.event.value).toString() : msg_tosend.event.value;    mqttClient.publish(topic, valToSend, pub_options, (err) => {`

**Comment by toddaustin07** [comment]
Thanks!  I'll make a similar change to the posted code after some regression tests of my own.
