### ISSUE TITLE
common.mylog is not a function

### ISSUE THREAD

**Issue by MABeatty1978** [toddaustin07/MQTT_SmartApp#3]
I'm trying to run the smartapps.js and I'm getting 
`Error: Cannot find module './common'`
If I edit the file to require 'common' (without the./) I get 
`TypeError: common.mylog is not a function`

I do have common installed
```
pi@mabpi:~/development/smartthings $ npm list
pi@ /home/pi
├── @smartthings/smartapp@4.0.0
├── common@0.2.5
└── express@4.18.2

```

Any help would be appreciated.  Thank you

**Comment by toddaustin07** [comment]
Do you have common.js downloaded from this repository and in the working directory where you are running smartapps.js?

**Comment by MABeatty1978** [comment]
I did not.  Thank you sir.

**Comment by MABeatty1978** [comment]
Missing native module.  Resolved.
