### ISSUE TITLE
Unrecognized App ID

### ISSUE THREAD

**Issue by Mouse703** [toddaustin07/MQTT_SmartApp#4]
I keep getting the error that my app ID is unrecognized. I have triple checked the app id in smartthings and it matches my app id that is in config.json. Any help would be appreciated.

smartapps.js output:
pi@framboostaart:~/smartthings/smartapps/MQTT_SmartApp $ node smartapps.js

Sat Jan 20 2024 13:25:17  Listening for SmartApp messages at 8083

Sat Jan 20 2024 13:25:27  HTTP POST received: CONFIGURATION for App ID f1ba33f5-1fb0-4e14-a32c-b8fd3351213c
 
POST message in ngrok:
{
    "lifecycle": "CONFIGURATION",
    "executionId": "397b0198-44b9-dee6-f649-2f2df8c9194f",
    "appId": "f1ba33f5-1fb0-4e14-a32c-b8fd3351213c",
    "locale": "en-gb",
    "version": "0.1.0",
    "client": {
        "os": "android",
        "version": "1.8.12.21",
        "language": "en-GB",
        "displayMode": "LIGHT",
        "timeZoneOffset": "",
        "supportedTemplates": [],
        "samsungAccountId": "",
        "mobileDeviceId": ""
    },
    "configurationData": {
        "installedAppId": "6e8cc8c5-67d9-44d5-a043-b2e63625a1b5",
        "phase": "INITIALIZE",
        "pageId": "",
        "previousPageId": "",
        "config": {}
    },
    "settings": {}
}

**Comment by toddaustin07** [comment]
Could you post the contents of your config.json?  Could it be as simple as a O instead of 0 or l instead of 1?

**Comment by Mouse703** [comment]
It would seem I was editing the wrong file, I reopend my config.json file and saw that it was blank.
